# Generated by Django 5.1.4 on 2024-12-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.BinaryField()),
            ],
        ),
    ]
