# Generated by Django 5.1.4 on 2024-12-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0002_rename_password_password_encrypted_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='encrypted_password',
        ),
        migrations.AddField(
            model_name='password',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='password',
            name='password_value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='login',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='password',
            name='service_name',
            field=models.CharField(max_length=255),
        ),
    ]
