# Generated by Django 5.1.4 on 2024-12-29 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0004_customtotpdevice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='login',
            new_name='encrypted_password',
        ),
        migrations.RemoveField(
            model_name='password',
            name='category',
        ),
        migrations.RemoveField(
            model_name='password',
            name='password_value',
        ),
        migrations.RemoveField(
            model_name='password',
            name='service_name',
        ),
        migrations.AddField(
            model_name='password',
            name='site',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_passwords', to=settings.AUTH_USER_MODEL),
        ),
    ]
